# Generated by Django 5.0.6 on 2024-06-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_featured_product_new_arrival_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured_product',
            name='description',
            field=models.TextField(default='Wearable'),
        ),
        migrations.AddField(
            model_name='new_arrival',
            name='description',
            field=models.TextField(default='Wearable'),
        ),
    ]
